name: Create Release

on:
  workflow_call:
    inputs:
      tag:
        description: "Release tag (sample 1.0.0)"
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: softprops/action-gh-release@v1
        id: create_release
        with:
          tag_name: ${{ inputs.tag }}
          name: v${{ inputs.tag }}
          draft: true
          prerelease: true
          generate_release_notes: true
