name: Website Deploy

on:
  workflow_call:

jobs:
  website-build:
    uses: ./.github/workflows/jobs/website-build.yaml
    with:
      upload-artifact: true

  website-deploy:
    needs: website-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: website-build
          path: build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
