import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'getting-started',
    'installation',
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/overview',
        'guides/oauth-setup',
        'guides/google-sheets-setup',
        'guides/editor-workflow',
        'guides/supported-versions',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/introduction',
      ],
    },
    {
      type: 'category',
      label: 'ADR',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'adr',
        },
      ],
    },
    'help',
  ],
};

export default sidebars;
