name: Pull Request Checks

on:
  pull_request:
    branches: [master]

jobs:
  dotnet-test-coverage:
    uses: ./.github/workflows/job-dotnet_test_coverage.yaml

  website-build:
    uses: ./.github/workflows/job-website_build.yaml
