name: Update Version Number

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "git tag you want create. (sample 1.0.0)"
        required: true
        type: string
      push-tag:
        description: "true = push tag. false = no push tag."
        required: false
        type: boolean
        default: true

  workflow_call:
    inputs:
      tag:
        description: "git tag you want create. (sample 1.0.0)"
        required: true
        type: string
      push-tag:
        description: "true = push tag. false = no push tag."
        required: false
        type: boolean
        default: true
    outputs:
      sha:
        description: "Git commit sha has changed."
        value: ${{ jobs.update-version-number.outputs.sha }}

jobs:
  update-version-number:
    name: Bump version to ${{ inputs.tag }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      sha: ${{ steps.commit.outputs.sha }}
    steps:
      - name: Store tag in output variable
        id: configure
        run: |
          echo "git-tag=${{ inputs.tag }}" | tee -a "$GITHUB_OUTPUT"

      - name: Checkout repository with push token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Run BumpVersion script for ${{ steps.configure.outputs.git-tag }}
        working-directory: .github/workflows/scripts
        run: dotnet run --file ./BumpVersion.cs ${{ inputs.tag }}

      - name: Check if files were modified
        id: check_update
        run: git diff --exit-code || echo "changed=1" | tee -a "$GITHUB_OUTPUT"

      - name: Commit version bump
        id: commit
        if: ${{ steps.check_update.outputs.changed == '1' }}
        run: |
          git config --local user.email ${{ secrets.ADMIN_EMAIL }}
          git config --local user.name ${{ secrets.ADMIN_NAME }}
          git commit -m "${{ steps.configure.outputs.git-tag }}" -a
          echo "sha=$(git rev-parse HEAD)" | tee -a "$GITHUB_OUTPUT"

      - name: Create git tag ${{ steps.configure.outputs.git-tag }}
        if: ${{ steps.check_update.outputs.changed == '1' && inputs.push-tag }}
        run: git tag ${{ steps.configure.outputs.git-tag }}

      - name: Push commit and tags to remote
        if: ${{ steps.check_update.outputs.changed == '1' }}
        run: |
          git push
          git push --tags
