name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: git tag you want create. (sample 1.0.0)"
        required: true

jobs:
  patch-versions:
    uses: ./.github/workflows/jobs/patch-versions.yaml
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets: inherit

  wait-for-action-status:
    needs: [patch-versions]
    if: needs.patch-versions.outputs.sha != ''
    uses: ./.github/workflows/jobs/wait-for-action-status.yaml
    with:
      sha: ${{ needs.patch-versions.outputs.sha }}
    secrets: inherit

  create-release:
    needs: [patch-versions, wait-for-action-status]
    if: ${{ !failure() && !cancelled() }}
    uses: ./.github/workflows/jobs/create-release.yaml
    with:
      tag: ${{ github.event.inputs.tag }}
